apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: petclinic
          image: ghcr.io/fareed7293-spec/spring-petclinic:sha-4062a130dc08e1169b112f25c7597992c40fb426
      #    image: ghcr.io/fareed7293-spec/spring-petclinic:sha-latest # Updated by Stage 7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: spring-petclinic
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
  selector:
    app: spring-petclinic
